name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to master branch.
        uses: actions/checkout@v1
      - name: Setup Nodejs.
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: $<!--swig￼0-->-js-$<!--swig￼1-->
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Generate README file
        run: yarn gen
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: $
